---
- name: Docker installing and configuration of docker 
  hosts: all 
  become: true 

  tasks: 
    - name: Updating the system 
      apt: 
        update_cache: yes

    - name: Installing docker
      apt:
        name: docker.io
        state: present

    - name: Starting the docker service  
      service:
        name: docker
        state: started
        enabled: yes
