---
- hosts: Masters
  become: true
  tasks:
    - name: Installing Docker
      apt:
        name: docker.io
        state: present

    - name: Installing Kubeadm, kubectl, and kubelet
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Initialize Kubernetes master
      command: "kubeadm init --pod-network-cidr=10.244.0.0/16"
      register: kubeadm_output
      ignore_errors: yes

    - name: Set up kubectl for the current user
      command: "{{ item }}"
      loop:
        - "mkdir -p $HOME/.kube"
        - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
        - "chown $(id -u):$(id -g) $HOME/.kube/config"
      when: kubeadm_output is succeeded

    - name: Install Calico network plugin
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when: "'calico' in kubeadm_output.stdout"

- hosts: workers
  become: true
  tasks:
    - name: Installing Docker
      apt:
        name: docker.io
        state: present

    - name: Installing Kubeadm, kubectl, and kubelet
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Join worker nodes to the cluster
      command: "{{ hostvars['masters']['kubeadm_output']['stdout'] }}"
      when: "'kubeadm join' in hostvars['masters']['kubeadm_output']['stdout']"
